# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description_text', models.CharField(max_length=500)),
                ('language', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('priority', models.BooleanField(default=False)),
                ('is_host_ntnui', models.BooleanField(default=False)),
                ('sports_group', models.ManyToManyField(null=True, to='groups.SportsGroup')),
            ],
        ),
        migrations.AddField(
            model_name='eventdescription',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Events'),
        ),
    ]
