# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180207_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sports_group',
            field=models.ManyToManyField(blank=True, null=True, to='groups.SportsGroup'),
        ),
    ]
