# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-07 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180307_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subeventdescription',
            old_name='category',
            new_name='sub_event',
        ),
    ]
