# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 14:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_auto_20180207_1503'),
        ('events', '0004_auto_20180216_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='sports_group',
        ),
        migrations.AddField(
            model_name='event',
            name='attending_members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='attending members'),
        ),
        migrations.AddField(
            model_name='event',
            name='sports_groups',
            field=models.ManyToManyField(blank=True, to='groups.SportsGroup', verbose_name='hosted by'),
        ),
    ]
