# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180216_1521'),
        ('events', '0005_auto_20180216_1532'),
    ]

    operations = [
    ]
