# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20180305_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_photo',
            field=models.ImageField(default='cover_photo/ntnui-volleyball.png', upload_to=events.models.Event.get_cover_upload_to),
        ),
    ]
