# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardchange',
            name='old_president_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardchange',
            name='president_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardchange',
            name='vice_president_approved',
            field=models.BooleanField(default=False),
        ),
    ]
