# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdoc',
            name='description',
            field=models.TextField(max_length=150),
        ),
    ]
