# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_boardchange_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardchange',
            name='vice_president_approved',
            field=models.BooleanField(default=True),
        ),
    ]
