strictness: medium
doc-warnings: false
test-warnings: false
autodetect: true
member-warnings: false

dodgy:
  run: false
pyflakes:
  run: false
pylint:
  disable:
    - unused-variable
    - unused-import
