# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171106_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_no',
            field=models.CharField(default=0, max_length=20, unique=True, verbose_name='customer no'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
