gantt
    title NTNUI Gantt Diagram
    dateFormat  YYYY-MM-DD
    section Sprints
    Sprint 1           :s1, 2017-09-06, 14d
    Sprint 2           :s2, 2017-09-20, 7d
    Sprint 3           :s3, 2017-09-27, 14d
    Sprint 4           :s3, 2017-10-11, 14d
    Sprint 5           :s3, 2020-10-25, d

    section Testing
        Accoun

    section Docs
    Create report           :s1, 2017-09-06, 7d
    another task      : 24d
