# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 09:51
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import groups.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='board_cashier', to=settings.AUTH_USER_MODEL)),
                ('president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                related_name='board_president', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.date.today)),
                ('paid', models.BooleanField(default=False)),
                ('role', models.CharField(default='member', max_length=50)),
                ('comment', models.CharField(blank=True, max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SportsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=12)),
                ('description', models.TextField(max_length=200)),
                ('public', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(default='thumbnail/ntnui2.svg',
                                                upload_to=groups.models.get_thumbnail_upload_to)),
                ('cover_photo', models.ImageField(default='cover_photo/ntnui-volleyball.png',
                                                  upload_to=groups.models.get_cover_upload_to)),
                ('active_board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                   related_name='active_board', to='groups.Board')),
                ('invitations', models.ManyToManyField(related_name='group_invitations',
                                                       through='groups.Invitation', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='group_members',
                                                   through='groups.Membership', to=settings.AUTH_USER_MODEL)),
                ('requests', models.ManyToManyField(related_name='group_requests',
                                                    through='groups.Request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='group',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='groups.SportsGroup'),
        ),
        migrations.AddField(
            model_name='request',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='group',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='groups.SportsGroup'),
        ),
        migrations.AddField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitation',
            name='group',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='groups.SportsGroup'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='board',
            name='sports_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='sports_group', to='groups.SportsGroup'),
        ),
        migrations.AddField(
            model_name='board',
            name='vice_president',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='board_vp', to=settings.AUTH_USER_MODEL),
        ),
    ]
