# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='in_board',
            field=models.BooleanField(default=False),
        ),
    ]
