# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='in_board',
        ),
        migrations.AddField(
            model_name='sportsgroup',
            name='active_board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_board', to='groups.Board'),
        ),
        migrations.AlterField(
            model_name='board',
            name='sports_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports_group', to='groups.SportsGroup'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(default='member', max_length=50),
        ),
    ]
