# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsgroup',
            name='active_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_board', to='groups.Board'),
        ),
    ]
