# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='sports_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports_group', to='groups.SportsGroup'),
        ),
    ]
