# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 10:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20171026_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='contract_type',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='membership',
            name='expiry_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
