# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20171026_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('cover_photo', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.SportsGroup')),
            ],
        ),
    ]
