# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20171106_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='comment',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
