# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20171101_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsgroup',
            name='active_board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_board', to='groups.Board'),
        ),
    ]
