# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_sportsgroup_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='paid_internal_license',
            field=models.BooleanField(default=False),
        ),
    ]
