# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_groupimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupimage',
            name='group',
        ),
        migrations.AddField(
            model_name='sportsgroup',
            name='cover_photo',
            field=models.ImageField(default='ntnui-icon.png', upload_to='cover_photos/<django.db.models.fields.CharField>'),
        ),
        migrations.AddField(
            model_name='sportsgroup',
            name='thumbnail',
            field=models.ImageField(default='ntnui-icon.png', upload_to='thumbnails/<django.db.models.fields.CharField>'),
        ),
        migrations.DeleteModel(
            name='GroupImage',
        ),
    ]
