# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20171026_1522'),
        ('groups', '0003_sportsgroup_active_board'),
    ]

    operations = [
    ]
