# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 12:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20171106_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(blank=True, max_length=3)),
                ('expiry_date', models.DateField(blank=True, default=datetime.date.today)),
            ],
        ),
        migrations.RemoveField(
            model_name='membership',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='contract',
            name='member',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='groups.Membership'),
        ),
    ]
