# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20171106_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='member',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
