# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_merge_20171105_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='in_board',
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(default='member', max_length=50),
        ),
    ]
