# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 19:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0004_auto_20170930_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='sportsgroup',
            name='members',
            field=models.ManyToManyField(related_name='group_members', through='groups.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.SportsGroup'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sportsgroup',
            name='invitations',
            field=models.ManyToManyField(related_name='group_invitations', through='groups.Invitation', to=settings.AUTH_USER_MODEL),
        ),
    ]
