# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20171001_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsgroup',
            name='description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
