# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import groups.models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20171105_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsgroup',
            name='cover_photo',
            field=models.ImageField(default='cover-photo/ntnui-volleyball.png', upload_to=groups.models.get_cover_upload_to),
        ),
        migrations.AlterField(
            model_name='sportsgroup',
            name='thumbnail',
            field=models.ImageField(default='thumbnail/ntnui2.svg', upload_to=groups.models.get_thumbnail_upload_to),
        ),
    ]
