# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_auto_20171005_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='date_issued',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sportsgroup',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
