# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_auto_20171002_0931'),
        ('groups', '0007_auto_20171005_1052'),
    ]

    operations = [
    ]
