# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-30 10:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_auto_20180322_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='CategoryDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('language', models.CharField(max_length=30, verbose_name='language')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'description',
                'verbose_name_plural': 'descriptions',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('registration_end_date', models.DateTimeField(blank=True, null=True, verbose_name='registration end date')),
                ('place', models.CharField(blank=True, max_length=50, verbose_name='place')),
                ('attendance_cap', models.IntegerField(blank=True, null=True, verbose_name='attendance cap')),
                ('priority', models.BooleanField(default=False, verbose_name='priority')),
                ('price', models.IntegerField(default=0, verbose_name='price')),
                ('is_host_ntnui', models.BooleanField(default=False, verbose_name='hosted by NTNUI')),
                ('cover_photo', models.ImageField(default='cover_photo/ntnui-volleyball.png', upload_to=events.models.Event.get_cover_upload_to)),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
        migrations.CreateModel(
            name='EventDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description_text', models.CharField(max_length=500, verbose_name='description')),
                ('custom_email_text', models.CharField(blank=True, max_length=250, null=True, verbose_name='email text')),
                ('language', models.CharField(max_length=30, verbose_name='language')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='event')),
            ],
            options={
                'verbose_name': 'event description',
                'verbose_name_plural': 'event descriptions',
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_time', models.DateTimeField(verbose_name='registration time')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment id')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='attendee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='event')),
            ],
            options={
                'verbose_name': 'attendee for event',
                'verbose_name_plural': 'attendees for event',
            },
        ),
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'restriction',
                'verbose_name_plural': 'restrictions',
            },
        ),
        migrations.CreateModel(
            name='SubEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('price', models.IntegerField(default=0, verbose_name='price')),
                ('attendance_cap', models.IntegerField(blank=True, null=True, verbose_name='attendance cap')),
                ('registration_end_date', models.DateTimeField(blank=True, null=True, verbose_name='registration end date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'sub-event',
                'verbose_name_plural': 'sub-events',
            },
        ),
        migrations.CreateModel(
            name='SubEventDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('language', models.CharField(max_length=30, verbose_name='language')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('custom_email_text', models.CharField(blank=True, max_length=250, null=True, verbose_name='email text')),
                ('sub_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.SubEvent', verbose_name='sub-event')),
            ],
            options={
                'verbose_name': 'description',
                'verbose_name_plural': 'descriptions',
            },
        ),
        migrations.CreateModel(
            name='SubEventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_time', models.DateTimeField(verbose_name='registration time')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='attendee')),
                ('sub_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.SubEvent', verbose_name='sub-event')),
            ],
            options={
                'verbose_name': 'attendee for sub-event',
                'verbose_name_plural': 'attendees for sub-event',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.AddField(
            model_name='subevent',
            name='tags',
            field=models.ManyToManyField(blank=True, to='events.Tag', verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='subevent',
            name='waiting_list',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='waiting list'),
        ),
        migrations.AddField(
            model_name='event',
            name='restriction',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='events.Restriction', verbose_name='restriction'),
        ),
        migrations.AddField(
            model_name='event',
            name='sports_groups',
            field=models.ManyToManyField(blank=True, to='groups.SportsGroup', verbose_name='hosted by'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, to='events.Tag', verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='event',
            name='waiting_list',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='waiting list'),
        ),
        migrations.AddField(
            model_name='category',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='event'),
        ),
        migrations.AlterUniqueTogether(
            name='subeventregistration',
            unique_together=set([('sub_event', 'attendee')]),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together=set([('event', 'attendee')]),
        ),
    ]
