# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-30 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subevent',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='subeventdescription',
            name='description',
        ),
        migrations.AlterField(
            model_name='event',
            name='cover_photo',
            field=models.ImageField(default='cover_photo/events/ntnui-volleyball.png', upload_to=events.models.Event.get_cover_upload_to),
        ),
    ]
