# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-26 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventguestregistration',
            options={'verbose_name': 'attendee, guest', 'verbose_name_plural': 'attendees, guests'},
        ),
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'verbose_name': 'attendee, user', 'verbose_name_plural': 'attendees, users'},
        ),
    ]
