# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-06 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventguestregistration',
            name='token',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='token'),
        ),
        migrations.AddField(
            model_name='eventguestwaitinglist',
            name='token',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='token'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='token',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='token'),
        ),
        migrations.AddField(
            model_name='eventwaitinglist',
            name='token',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='token'),
        ),
        migrations.AddField(
            model_name='subeventguestregistration',
            name='token',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='token'),
        ),
        migrations.AddField(
            model_name='subeventguestwaitinglist',
            name='token',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='token'),
        ),
        migrations.AddField(
            model_name='subeventregistration',
            name='token',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='token'),
        ),
        migrations.AddField(
            model_name='subeventwaitinglist',
            name='token',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='token'),
        ),
    ]
