# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-24 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180325_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subevent',
            name='attending_members',
        ),
    ]
