# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-24 23:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_subevent_attending_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subevent',
            name='attending_members',
        ),
        migrations.AddField(
            model_name='event',
            name='waiting_list',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='waiting list'),
        ),
        migrations.AddField(
            model_name='subevent',
            name='waiting_list',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='waiting list'),
        ),
    ]
