# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 12:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20180325_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'verbose_name': 'attendee for event', 'verbose_name_plural': 'attendees for event'},
        ),
        migrations.AlterModelOptions(
            name='restriction',
            options={'verbose_name': 'restriction', 'verbose_name_plural': 'restrictions'},
        ),
        migrations.AlterModelOptions(
            name='subevent',
            options={'verbose_name': 'sub-event', 'verbose_name_plural': 'sub-events'},
        ),
        migrations.AlterModelOptions(
            name='subeventregistration',
            options={'verbose_name': 'attendee for sub-event', 'verbose_name_plural': 'attendees for sub-event'},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='place',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='attendee'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='registration_time',
            field=models.DateTimeField(verbose_name='registration time'),
        ),
        migrations.AlterField(
            model_name='subeventdescription',
            name='sub_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.SubEvent', verbose_name='sub-event'),
        ),
        migrations.AlterField(
            model_name='subeventregistration',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='attendee'),
        ),
        migrations.AlterField(
            model_name='subeventregistration',
            name='registration_time',
            field=models.DateTimeField(verbose_name='registration time'),
        ),
        migrations.AlterField(
            model_name='subeventregistration',
            name='sub_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.SubEvent', verbose_name='sub-event'),
        ),
    ]
