# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20180326_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='location',
            new_name='place',
        ),
    ]
