# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20180401_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdescription',
            name='custom_email_text',
            field=models.CharField(max_length=250, null=True, verbose_name='email text'),
        ),
        migrations.AddField(
            model_name='subeventdescription',
            name='custom_email_text',
            field=models.CharField(max_length=250, null=True, verbose_name='email text'),
        ),
    ]
