# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20180401_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.FloatField(default=0, verbose_name='price'),
        ),
    ]
