# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_registration_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subevent',
            name='registration_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='registration end date'),
        ),
    ]
