# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20180404_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='subeventdescription',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='description'),
        ),
    ]
