# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.FloatField(blank=True, default=0, verbose_name='price'),
        ),
    ]
