# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20180404_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='price'),
        ),
    ]
