# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20180404_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.IntegerField(default=0, verbose_name='price'),
        ),
    ]
