# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20180404_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdescription',
            name='custom_email_text',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='email text'),
        ),
        migrations.AlterField(
            model_name='subeventdescription',
            name='custom_email_text',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='email text'),
        ),
    ]
