# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20180404_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment id'),
        ),
    ]
