# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-12 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_subevent_registration_end_date'),
        ('events', '0012_auto_20180404_1648'),
        ('events', '0013_eventregistration_payment_id'),
    ]

    operations = [
    ]
