# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-25 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_merge_20180412_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('phone_number', models.IntegerField(max_length=8, verbose_name='phone number')),
            ],
            options={
                'verbose_name': 'guest',
                'verbose_name_plural': 'guests',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='guest_attendees',
            field=models.ManyToManyField(blank=True, to='events.Guest', verbose_name='guest attendees'),
        ),
    ]
