# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-25 07:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20180425_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='guest_attendees',
        ),
        migrations.AddField(
            model_name='subeventregistration',
            name='guest_attendee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Guest', verbose_name='guest attendee'),
        ),
        migrations.AlterField(
            model_name='subeventregistration',
            name='attendee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='attendee'),
        ),
    ]
