@startuml

package groups.tests.mixins.general <<Rectangle>> {
  abstract class LoggedInMixin
  abstract class GroupMixin {
    + test_status_code_200()
    + test_should_contain_group_name()
    + test_should_link_to_about()
  }
  abstract class GeneralMemberMixin {
    + test_should_not_link_to_members()
    + test_should_not_link_to_settings()
  }
  abstract class CoreBoardMemberMixin {
    + test_should_link_to_members()
  }
  abstract class GeneralBoardMemberMixin {
    + test_should_not_link_to_settings()
  }
  abstract class GeneralGroupLeaderMixin {
    + test_should_link_to_settings()
  }
}

package Members {

  package groups.tests.mixins.view_members <<Rectangle>> {
    abstract class VM_CoreBoardMemberMixin {
      + test_contains_all_members()
      + test_total_count_members()
      + test_total_count_invitations()
      + test_should_link_to_invitations()
      + test_view_function()
    }
    abstract class VM_BoardMemberMixin {
      + test_should_not_link_to_new_invite()
    }
    abstract class VM_GroupLeaderMixin {
      + test_should_link_to_new_invite()
    }
  }


  package groups.test_view_group_members <<Rectangle>> {
    class MemberTest {
      + test_contains_no_members()
      + test_shoud_contain_members_error_text()
      + test_should_not_link_to_inviations()
      + test_should_not_link_to_new_invite()
    }
    class CashierTest
    class VicePresidentTest
    class PresidentTest
    class GroupMembersLoggedOutTest {
      + test_status_code_302()
    }
    class NoGroupTest {
      + test_status_code_404()
      + test_view_function()
    }
  }

  LoggedInMixin *-- GroupMixin
  GroupMixin *-- CoreBoardMemberMixin
  GroupMixin *-- GeneralMemberMixin
  CoreBoardMemberMixin *-- GeneralBoardMemberMixin
  CoreBoardMemberMixin *-- GeneralGroupLeaderMixin
  VM_CoreBoardMemberMixin *-- VM_BoardMemberMixin
  GeneralBoardMemberMixin *-- VM_BoardMemberMixin
  VM_CoreBoardMemberMixin *-- VM_GroupLeaderMixin
  GeneralGroupLeaderMixin *-- VM_GroupLeaderMixin
  GeneralMemberMixin *-- MemberTest
  VM_BoardMemberMixin *-- CashierTest
  VM_GroupLeaderMixin *-- VicePresidentTest
  VM_GroupLeaderMixin *-- PresidentTest

}

package AboutGroup {
  package groups.tests.mixins.view_about <<Rectangle>> {
    class VA_CoreMemberMixin {
      - test_view_function()
      - test_has_description()
      - test_has_total_count_board_members()
    }
  }


  package groups.tests.test_view_group_about <<Rectangle>> {
    class GroupAboutLoggedOutTest {
      + test_status_code()
    }
    together {
      class ViewAboutMemberTest
      class ViewAboutCashierTest
      class ViewAboutVicePresidentTest
      class ViewAboutPresidentTest
    }

  }

  GeneralMemberMixin *- ViewAboutMemberTest
  VA_CoreMemberMixin *-- ViewAboutMemberTest

  GeneralBoardMemberMixin *--- ViewAboutCashierTest
  VA_CoreMemberMixin *- ViewAboutCashierTest

  GeneralGroupLeaderMixin *-- ViewAboutVicePresidentTest
  VA_CoreMemberMixin *-- ViewAboutVicePresidentTest

  GeneralGroupLeaderMixin *-- ViewAboutPresidentTest
  VA_CoreMemberMixin *-- ViewAboutPresidentTest
}

package Invitations {
  package groups.tests.mixins.view_invitations <<Rectangle>> {
    class VI_CoreBoardMemberMixin {
      - test_view_function()
      - test_contains_all_invitations()
      - test_total_count_invitations()
      - test_total_count_members()
      - test_should_link_to_members()
    }
    class VI_BoardMemberMixin {
      - test_should_not_link_to_new_invite()
    }
    class VI_GroupLeaderMixin {
      - test_should_link_to_new_invite()
    }

    VI_CoreBoardMemberMixin *-- VI_BoardMemberMixin
    VI_CoreBoardMemberMixin *-- VI_GroupLeaderMixin
  }

  package groups.tests.test_view_group_invitations <<Rectangle>> {
    class GroupAboutLoggedOutTest {
      + test_status_code()
    }

    class ViewInvitationMemberTest {
      - test_view_function()
      - test_should_contain_error_text()
      - test_should_not_link_to_inviations()
      - test_should_not_link_to_new_invite()
    }
    class ViewInvitationCashierTest
    class ViewInvitationVicePresidentTest
    class ViewInvitationPresidentTest

    GeneralMemberMixin *-- ViewInvitationMemberTest
    VI_BoardMemberMixin *-- ViewInvitationCashierTest
    VI_GroupLeaderMixin *-- ViewInvitationVicePresidentTest
    VI_GroupLeaderMixin *-- ViewInvitationPresidentTest
  }

  GeneralBoardMemberMixin *-- VI_CoreBoardMemberMixin
  GeneralGroupLeaderMixin *-- VI_GroupLeaderMixin
}



@enduml
